### ISSUE TITLE
Attempt to index nil with connect?

### ISSUE THREAD

**Issue by Atharv-Khatri** [1ForeverHD/UtilityModules#3]
I dont really understand this error 
![image](https://user-images.githubusercontent.com/62333550/79232245-e28e9780-7e84-11ea-98a2-9d3f24e0a212.png)

Code-
```lua
local players = game:GetService("Players")
local replicatedStorage = game:GetService("ReplicatedStorage")
local Zone = require(replicatedStorage.Modules.ZonePlus)



-- INIT ZONE
local newZoneGroup = script.Parent
local newZone = Zone.new(newZoneGroup)
newZone.PlayerAdded:Connect(function(player)
	print(player.Name, "entered zone:", newZoneGroup.Name)
end)
newZone.PlayerRemoving:Connect(function(player)
	print(player.Name, "exited zone:", newZoneGroup.Name)
end)
newZone:initLoop()

```

I havent changed anything in the module

**Comment by 1ForeverHD** [comment]
Hi Atharv,

The zone's properties are now in camelCase as apposed to PascalCase to conform with the lua styling guide. Try ``newZone.playerAdded`` and ``newZone.playerRemoving`` instead.

**Comment by Atharv-Khatri** [comment]
Thank you
